### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by shanow7** [darkcode357/blackdog#113]
![image](https://user-images.githubusercontent.com/37192410/121425392-a2388580-c972-11eb-951a-5c17688cd06b.png)

**Comment by darkcode357** [comment]
the installation error is being shown on the screen, on some linux distributions, the path usr/bin and local/bin may not be configured in your path

add solution to your path

/usr/local/bin/
$HOME/.local/bin/

1- echo $PATH
2-export PATH=$PATH:/usr/local/sbin
3-export PATH=$PATH:$HOME/.local/bin/

**Comment by shanow7** [comment]
![image](https://user-images.githubusercontent.com/37192410/121816945-d667bb00-cc7e-11eb-8146-7836645a1ee9.png)

**Comment by darkcode357** [comment]
![image](https://user-images.githubusercontent.com/24551924/121916056-2dff3880-cd0a-11eb-9d12-772982de17c0.png)
![image](https://user-images.githubusercontent.com/24551924/121916135-42dbcc00-cd0a-11eb-8a36-638e6ae93230.png)
![image](https://user-images.githubusercontent.com/24551924/121916212-52f3ab80-cd0a-11eb-9c01-29d3a630a724.png)
https://github.com/darkcode357/blackdog/blob/7ab1c5b5c3fe3a9a56d96451a62fde150d50870c/pyproject.toml
fixed
